# Combining 1997-2022 Filtered DFs

## Imports

In [2]:
import pandas as pd

In [3]:
df_2022 = pd.read_csv("/Users/abby/Desktop/RAFI/infogroup_csvs/poultry_plants_2022.csv")
df_2021 = pd.read_csv("/Users/abby/Desktop/RAFI/infogroup_csvs/poultry_plants_2021.csv")
df_2020 = pd.read_csv("/Users/abby/Desktop/RAFI/infogroup_csvs/poultry_plants_2020.csv")
df_2019 = pd.read_csv("/Users/abby/Desktop/RAFI/infogroup_csvs/poultry_plants_2019.csv")
df_2018 = pd.read_csv("/Users/abby/Desktop/RAFI/infogroup_csvs/poultry_plants_2018.csv")
df_2017 = pd.read_csv("/Users/abby/Desktop/RAFI/infogroup_csvs/poultry_plants_2017.csv")
df_2016 = pd.read_csv("/Users/abby/Desktop/RAFI/infogroup_csvs/poultry_plants_2016.csv")
df_2015 = pd.read_csv("/Users/abby/Desktop/RAFI/infogroup_csvs/poultry_plants_2015.csv")
df_2014 = pd.read_csv("/Users/abby/Desktop/RAFI/infogroup_csvs/poultry_plants_2014.csv")
df_2013 = pd.read_csv("/Users/abby/Desktop/RAFI/infogroup_csvs/poultry_plants_2013.csv")
df_2012 = pd.read_csv("/Users/abby/Desktop/RAFI/infogroup_csvs/poultry_plants_2012.csv")
df_2011 = pd.read_csv("/Users/abby/Desktop/RAFI/infogroup_csvs/poultry_plants_2011.csv")
df_2010 = pd.read_csv("/Users/abby/Desktop/RAFI/infogroup_csvs/poultry_plants_2010.csv")
df_2009 = pd.read_csv("/Users/abby/Desktop/RAFI/infogroup_csvs/poultry_plants_2009.csv")
df_2008 = pd.read_csv("/Users/abby/Desktop/RAFI/infogroup_csvs/poultry_plants_2008.csv")
df_2007 = pd.read_csv("/Users/abby/Desktop/RAFI/infogroup_csvs/poultry_plants_2007.csv")
df_2006 = pd.read_csv("/Users/abby/Desktop/RAFI/infogroup_csvs/poultry_plants_2006.csv")
df_2005 = pd.read_csv("/Users/abby/Desktop/RAFI/infogroup_csvs/poultry_plants_2005.csv")
df_2004 = pd.read_csv("/Users/abby/Desktop/RAFI/infogroup_csvs/poultry_plants_2004.csv")
df_2003 = pd.read_csv("/Users/abby/Desktop/RAFI/infogroup_csvs/poultry_plants_2003.csv")
df_2002 = pd.read_csv("/Users/abby/Desktop/RAFI/infogroup_csvs/poultry_plants_2002.csv")
df_2001 = pd.read_csv("/Users/abby/Desktop/RAFI/infogroup_csvs/poultry_plants_2001.csv")
df_2000 = pd.read_csv("/Users/abby/Desktop/RAFI/infogroup_csvs/poultry_plants_2000.csv")
df_1999 = pd.read_csv("/Users/abby/Desktop/RAFI/infogroup_csvs/poultry_plants_1999.csv")
df_1998 = pd.read_csv("/Users/abby/Desktop/RAFI/infogroup_csvs/poultry_plants_1998.csv")
df_1997 = pd.read_csv("/Users/abby/Desktop/RAFI/infogroup_csvs/poultry_plants_1997.csv")

## Standardizing Column Names

In [4]:
df_2021.columns = map(str.upper, df_2021.columns)
df_2020.columns = map(str.upper, df_2020.columns)
df_2019.columns = map(str.upper, df_2019.columns)
df_2018.columns = map(str.upper, df_2018.columns)
df_2017.columns = map(str.upper, df_2017.columns)
df_2016.columns = map(str.upper, df_2016.columns)
df_2015.columns = map(str.upper, df_2015.columns)
df_2014.columns = map(str.upper, df_2014.columns)
df_2013.columns = map(str.upper, df_2013.columns)
df_2012.columns = map(str.upper, df_2012.columns)
df_2011.columns = map(str.upper, df_2011.columns)
df_2010.columns = map(str.upper, df_2010.columns)
df_2009.columns = map(str.upper, df_2009.columns)
df_2008.columns = map(str.upper, df_2008.columns)
df_2007.columns = map(str.upper, df_2007.columns)
df_2006.columns = map(str.upper, df_2006.columns)
df_2005.columns = map(str.upper, df_2005.columns)
df_2004.columns = map(str.upper, df_2004.columns)
df_2003.columns = map(str.upper, df_2003.columns)
df_2002.columns = map(str.upper, df_2002.columns)
df_2001.columns = map(str.upper, df_2001.columns)
df_2000.columns = map(str.upper, df_2000.columns)
df_1999.columns = map(str.upper, df_1999.columns)
df_1998.columns = map(str.upper, df_1998.columns)
df_1997.columns = map(str.upper, df_1997.columns)

## Concatinating DFs

In [5]:
df_1997_2022 = pd.DataFrame()

In [6]:
df_1997_2022 = pd.concat([df_1997_2022, df_2022], ignore_index=True)
df_1997_2022 = pd.concat([df_1997_2022, df_2021], ignore_index=True)

In [7]:
df_1997_2022 = pd.concat([df_1997_2022, df_2020], ignore_index=True)
df_1997_2022 = pd.concat([df_1997_2022, df_2019], ignore_index=True)
df_1997_2022 = pd.concat([df_1997_2022, df_2018], ignore_index=True)
df_1997_2022 = pd.concat([df_1997_2022, df_2017], ignore_index=True)
df_1997_2022 = pd.concat([df_1997_2022, df_2016], ignore_index=True)
df_1997_2022 = pd.concat([df_1997_2022, df_2015], ignore_index=True)
df_1997_2022 = pd.concat([df_1997_2022, df_2014], ignore_index=True)
df_1997_2022 = pd.concat([df_1997_2022, df_2013], ignore_index=True)
df_1997_2022 = pd.concat([df_1997_2022, df_2012], ignore_index=True)
df_1997_2022 = pd.concat([df_1997_2022, df_2011], ignore_index=True)
df_1997_2022 = pd.concat([df_1997_2022, df_2010], ignore_index=True)
df_1997_2022 = pd.concat([df_1997_2022, df_2009], ignore_index=True)
df_1997_2022 = pd.concat([df_1997_2022, df_2008], ignore_index=True)
df_1997_2022 = pd.concat([df_1997_2022, df_2007], ignore_index=True)
df_1997_2022 = pd.concat([df_1997_2022, df_2006], ignore_index=True)
df_1997_2022 = pd.concat([df_1997_2022, df_2005], ignore_index=True)
df_1997_2022 = pd.concat([df_1997_2022, df_2004], ignore_index=True)
df_1997_2022 = pd.concat([df_1997_2022, df_2003], ignore_index=True)
df_1997_2022 = pd.concat([df_1997_2022, df_2002], ignore_index=True)
df_1997_2022 = pd.concat([df_1997_2022, df_2001], ignore_index=True)
df_1997_2022 = pd.concat([df_1997_2022, df_2000], ignore_index=True)
df_1997_2022 = pd.concat([df_1997_2022, df_1999], ignore_index=True)
df_1997_2022 = pd.concat([df_1997_2022, df_1998], ignore_index=True)
df_1997_2022 = pd.concat([df_1997_2022, df_1997], ignore_index=True)

## Final DF

In [8]:
df_1997_2022

,Unnamed: 0,COMPANY,ADDRESS LINE 1,CITY,STATE,ZIPCODE,ZIP4,COUNTY CODE,AREA CODE,IDCODE,...,MAILING CITY,MAILING STATE,MAILING ZIPCODE,MAILING ZIP4,MAILING ADDRESS FLAG,UNIT NUMBER,UNIT TYPE,NAICS CODE,PROFESSIONAL SIC FLAG,SIC6_DESCRIPTIONS (PRIMARYSIC)
0,11380.0,COOTERS FARM,1784 TUCK WILKES RD,NOXAPATER,MS,39346.0,9311.0,159.0,662.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21772.0,TYSON FOODS INC,47283 SD HIGHWAY 34,COLMAN,SD,57017.0,6543.0,101.0,605.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21912.0,SIMMONS FOODS INC,2101 TWIN CIRCLE DR,VAN BUREN,AR,72956.0,6027.0,33.0,479.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,39534.0,TYSON FOODS INC,605 235-3301 #DD813,NORTH SIOUX CITY,SD,57049.0,NaN,127.0,605.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,74599.0,MAR-JAC POULTRY INC,1301 JAMES ST,HATTIESBURG,MS,39401.0,4570.0,35.0,601.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16338,NaN,GARY R WEST TASTING ROOM,690 N 5TH ST,JACKSONVILLE,OR,97530.0,9659.0,29.0,541.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16339,NaN,ACME POULTRY CO,1024 S KING ST,SEATTLE,WA,98104.0,3097.0,33.0,206.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16340,NaN,DRAPER VALLEY FARMS INC,1000 JASON LN,MT VERNON,WA,98273.0,NaN,57.0,360.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16341,NaN,STARKEL POULTRY INC,10524 128TH ST E,PUYALLUP,WA,98374.0,3044.0,53.0,253.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16342,NaN,PEDERSON'S FRYER FARMS INC,2901 72ND ST E,TACOMA,WA,98404.0,4199.0,53.0,253.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df_1997_2022.columns

Index(['Unnamed: 0', 'COMPANY', 'ADDRESS LINE 1', 'CITY', 'STATE', 'ZIPCODE',
       'ZIP4', 'COUNTY CODE', 'AREA CODE', 'IDCODE',
       'LOCATION EMPLOYEE SIZE CODE', 'LOCATION SALES VOLUME CODE',
       'PRIMARY SIC CODE', 'SIC6_DESCRIPTIONS', 'PRIMARY NAICS CODE',
       'NAICS8 DESCRIPTIONS', 'SIC CODE', 'SIC6_DESCRIPTIONS (SIC)',
       'SIC CODE 1', 'SIC6_DESCRIPTIONS (SIC1)', 'SIC CODE 2',
       'SIC6_DESCRIPTIONS(SIC2)', 'SIC CODE 3', 'SIC6_DESCRIPTIONS(SIC3)',
       'SIC CODE 4', 'SIC6_DESCRIPTIONS(SIC4)', 'ARCHIVE VERSION YEAR',
       'YELLOW PAGE CODE', 'EMPLOYEE SIZE (5) - LOCATION',
       'SALES VOLUME (9) - LOCATION', 'BUSINESS STATUS CODE',
       'INDUSTRY SPECIFIC FIRST BYTE', 'YEAR ESTABLISHED', 'OFFICE SIZE CODE',
       'COMPANY HOLDING STATUS', 'ABI', 'SUBSIDIARY NUMBER', 'PARENT NUMBER',
       'PARENT ACTUAL EMPLOYEE SIZE', 'PARENT ACTUAL SALES VOLUME',
       'PARENT EMPLOYEE SIZE CODE', 'PARENT SALES VOLUME CODE', 'SITE NUMBER',
       'ADDRESS TYPE INDICATOR', 'POPULATION CODE', 'CENSUS TRACT',
       'CENSUS BLOCK', 'LATITUDE', 'LONGITUDE', 'MATCH CODE', 'CBSA CODE',
       'CBSA LEVEL', 'CSA CODE', 'FIPS CODE', 'UNNAMED: 0', 'FIRST NAME',
       'LAST NAME', 'PHONE NUMBER', 'FAX AREA CODE', 'FAX PHONE NUMBER',
       'PROFESSIONAL TITLE', 'TITLE CODE', 'GENDER',
       'EMPLOYEE SIZE (6) - CORPORATE', 'MODELED EMPLOYEE SIZE',
       'SALES VOLUME (9) - CORPORATE', 'CALL STATUS CODE',
       'NAME STANDARIZATION FLAG', 'SQUARE FOOTAGE', 'AD SIZE CODE',
       'BOOK NUMBER', 'ARCHIVE VERSION MONTH', 'NEW ADD DATE',
       'TELERESEARCH UPDATE DATE', 'YEAR 1ST APPEARED', 'LOCATION NAME',
       'LANDMARK ADDRESS', 'LANDMARK CITY', 'LANDMARK STATE',
       'LANDMARK ZIPCODE', 'LANDMARK ZIP4', 'MAILING ADDRESS', 'MAILING CITY',
       'MAILING STATE', 'MAILING ZIPCODE', 'MAILING ZIP4',
       'MAILING ADDRESS FLAG', 'UNIT NUMBER', 'UNIT TYPE', 'NAICS CODE',
       'PROFESSIONAL SIC FLAG', 'SIC6_DESCRIPTIONS (PRIMARYSIC)'],
      dtype='object')

In [10]:
ALL = "/Users/abby/Desktop/RAFI/1997-2022_poultry_plants.csv"
df_1997_2022.to_csv(ALL)